services:
  # 1. Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: password_manager_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: passwordvault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Backend API (.NET)
  backend:
    build:
      context: ./backend
      target: build
    container_name: password_manager_api
    depends_on:
      - db
    command: dotnet watch run --urls "http://*:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=passwordvault;Username=admin;Password=adminpassword
      - EncryptionSettings__Key=12345678901234567890123456789012
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - JwtSettings__Key=EstaEUmaChaveMuitoLongaParaGarantirQueOSHA512NaoReclameDeFaltaDeBitsSegurancaMaxima12345678901234567890
    ports:
      - "5000:8080"
    volumes:
      - ./backend:/app
      - /app/obj
      - /app/bin

  # 3. Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      target: build 
    container_name: password_manager_ui
    depends_on:
      - backend
    command: npm run dev -- --host --port 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app 
      - /app/node_modules 

volumes:
  pgdata: